name: CI/CD

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    name: Tests de l'application
    runs-on: ubuntu-latest
    steps:
      - name: Récupère la version courante du dépôt git
        uses: actions/checkout@v2
      - name: Paramétrage de nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "18.8.0"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Installation des dépendances
        run: npm install
      - name: Lancement des tests unitaires
        run: npm run test
      - name: Lancement des tests de bout en bout
        run: |
          npm start &
          npm run test:e2e-ci
